package oop.exception.exception1;

public class FinallyTest2 {
    public static void main(String[] args) {

    }
}
